# Database settings
database:
  type: SQLITE   # SQLITE, MYSQL, or MARIADB
  mysql:
    host: localhost
    port: 3306
    database: solarelo
    username: root
    password: password
    pool-size: 10

config-version: "1.5"
